### ISSUE TITLE
cant get flyback converter to work

### ISSUE THREAD

**Issue by flankerzo** [NiklasFauth/pcbtc#8]
Hi, i have trouble to get flyback to work, i got almost zero voltage on 50v side. I designed my own pcb, with some cosmetic changes. If i feed it from anotther power supply it works nice :) 
I tried to measure PWM on pin29 (PA8) and got 0 volts, and no duty cycle.
I also tried looking in code, but i cant get it open as project in stm cube ide...,

**Comment by lucysrausch** [comment]
Hey!

The flyback is only enabled after successful connection to you computer.
Did you check if the tesla coil shows up as a MIDI device?
If not, I would start looking for a problem around the STM32. Did you flash it via DFU? Did this work correctly?

Best
Niklas

**Comment by flankerzo** [comment]
Hi, 

yes it shows in device manager as PCB MIDI Tesla Coil [0-3], i used Midi Player 5 to play some songs, selected midi output PCB MIDI TESLA COIL i used another psu, to power it.
I tried measure with osciloscope when playing songs, but i got no PWM., its in high impedance state. If i remowed 5k resistor from pin 29 i can switch it with bare finger.
I have used stm32cube programmer to flash it.

Thanks for response :)
Patrik

**Comment by flankerzo** [comment]
HI,

Hmm i think i found problem, i used STM32F072CBU6 and i see in your schematic c8ux .... achhh , im suprised it works somehow...  can it be compiled for this mcu please? or i need to swap it?
thanks

Patrik

**Comment by lucysrausch** [comment]
I'm not sure if halve the ram would be sufficient.
I compiled the firmware with the STM32F072C8Tx_FLASH.ld. You can download it from here:
http://cloud.otter.jetzt/s/DDaeNxdXroBXzqc

I didn't tested this at all, I just compiled it. Use on your own risk.
If you still have problems, please consider replacing the STM32.

**Comment by flankerzo** [comment]
It works, Thanks !
I found out, that rectifing shottky diodes (D11,D13) are 100V, i blow them up. I used 600V diodes, fixed problem.  
I changed feedback, added in parrarel to USBCL6 some BAV21, and 5V6 zener diodes (5V and GND), its more stable and can work with lower voltage. 
And added another safety diodes to H bridge.
:) 
Patrik

**Comment by judge2005** [comment]
Hi Patrik, do you have a set of PCBs you could sell me?

**Comment by flankerzo** [comment]
yes i have, but designed by me., they have some ups and cons. I think it will be better for you, to order 
original from jlcpcb, if you export it with pick n place data and bom they can also solder one side of board, i payed 45 bucks for 3 sets pcb, 1 set 5 pcb. But if you insist i can sold you mine, but the shipping from my country will be similiar to new made pcbs ... :(
